AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Luminova Admin API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11

Parameters:
  JwtSecret:
    Type: String
    NoEcho: true
  AdminUserId:
    Type: String
    Default: luminovatech
  AdminPassword:
    Type: String
    NoEcho: true
  FrontendOrigin:
    Type: String
    Default: https://luminova-new.vercel.app
  S3ResumeBucket:
    Type: String
    Default: luminva-profile-store
  GoogleDriveFolderId:
    Type: String
    Default: ""
  DynamoTablePrefix:
    Type: String
    Default: luminova_

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  AdminApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Events:
        RootEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DYNAMODB_TABLE_PREFIX: !Ref DynamoTablePrefix
          JWT_SECRET: !Ref JwtSecret
          JWT_ALGORITHM: HS256
          JWT_EXPIRE_HOURS: "8"
          FRONTEND_ORIGIN: !Ref FrontendOrigin
          S3_RESUME_BUCKET: !Ref S3ResumeBucket
          GOOGLE_SERVICE_ACCOUNT_JSON: '{{resolve:ssm:/luminova/google-service-account-json}}'
          GOOGLE_DRIVE_FOLDER_ID: !Ref GoogleDriveFolderId
          ADMIN_USER_ID: !Ref AdminUserId
          ADMIN_PASSWORD: !Ref AdminPassword
      Policies:
        - DynamoDBCrudPolicy:
            TableName: luminova_resources
        - DynamoDBCrudPolicy:
            TableName: luminova_jobs
        - DynamoDBCrudPolicy:
            TableName: luminova_employees
        - DynamoDBCrudPolicy:
            TableName: luminova_admin_users
        - S3CrudPolicy:
            BucketName: !Ref S3ResumeBucket
        - SSMParameterReadPolicy:
            ParameterName: luminova/google-service-account-json

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/'
